INSERT INTO `announcements` (`id_announcements`, `date`, `title`, `text`) VALUES
(1, '2023-09-01 10:00:00', '<p>The <strong>ESA Exeter app</strong> is online! </p><br>', 
'<br>ESA Exeter 2023 app is ready to serve you during the conference. It has an easy to remember address: <strong>https://esa.feele.exeter.ac.uk/</strong> </p> <p>With this app, you can: </p> <ul> <li>Browse talks by date and session,</li> <li>Add sessions on your program,</li> <li>Search for papers,</li> <li>Take a look at the list of participants,</li> <li>And see some other information about the conference.</li> </ul> <p>Please note that we are currently in the beta stage. If you experince issues with the up or notice bugs, please send us an email: <a href=""mailto:abc123.com.com"">???</a></p>');

INSERT INTO `date_arrays` (`id_date_arrays`, `id_day`, `day`) VALUES
(1,	'd0', '11 September 2023'),
(2,	'd1', '12 September 2023'),
(3,	'd2', '13 September 2023');

INSERT INTO `joint_event` (`id_joint_event`, `sid`, `timeslot`, `room`, `event_name`, `event_title`, `event_summary`, `event_presenter_fname`, `event_presenter_lname`) VALUES
(1, 'd0_s01_rExeter', '17:00 - 19:00', 'Exeter Castle', 'Social Events', 'Welcome Reception', 'There will be a welcome reception on September 11th at the Exeter Castle. This event has been made possible through the generous sponsorship of the University of Exeter Business School.<br>A registration desk will be available at the venue. The Castle of Exeter stands atop the highest part of the city, within the north-east angle of the city walls. From the reddish colour of the volcanic rock on which it stood; it became known locally as Rougemont Castle.', '', ''),
(2, 'd1_s01_rExeter', '09:00 - 10:15', 'Streatham Court A', 'Keynote Lecture - Katie B. Coffman', 'Chair', 'Katie B. Coffman is the Piramal Associate Professor of Business Administration in the Negotiations, Organizations & Market unit. Before joining HBS, she was an assistant professor of economics at The Ohio State University and a visiting assistant professor of economics at Stanford University. In her research, Katie uses experimental methods to study individual, team, and managerial decision making, with a focus on the role of gender stereotypes in shaping beliefs. Her work has been published in Management Science, the American Economic Review, the Quarterly Journal of Economics, and Social Choice and Welfare amongst others. She is an associate editor of Management Science and the Journal of Political Economy: Microeconomics. Katie holds a PhD in economics from Harvard University and a BA in mathematics and economics from Williams College.', 'Brit', 'Grosskopf'),
(3, 'd1_s02_rExeter', '13:00 - 14:15', 'Streatham Court A', 'Panel Session - State of the Art of Online Experiments', 'Chair', 'There has been an increase in online experiments fuelled by the ease of conducting them, their relatively low costs and last but not least because of necessity induced by the Covid pandemic. While we have clear guidelines on how to conduct laboratory experiments, less structure exists for conducting online experiments. This round table discussion aims to address this void and establish a state of the art of conducting online experiments. Panellists: •	Andrew Gordon (Prolific)\n•	Dorothea Kübler (WZB)\n•	Bobby Stuijfzand (Behavioural Insights Team)\n•Alistair Wilson (Pitt)', 'Edwin', 'Ip'),
(4, 'd1_s03_rExeter', '19:45 - 22:00', 'Exeter Cathedral', 'Social Events', 'Conference Dinner', 'The conference dinner will be held at the Exeter Cathedral. Exeter Cathedral, properly known as the Cathedral Church of Saint Peter in Exeter, is an Anglican cathedral, and the seat of the Bishop of Exeter. The present building was complete by about 1400 and has several notable features, including an early set of misericords, an astronomical clock and the longest uninterrupted medieval stone vaulted ceiling in the world.', '', ''),
(5, 'd2_s01_rExeter', '09:00 - 10:00', 'Streatham Court A', 'Keynote Lecture - Steffen Huck', 'Chair', 'Steffen Huck is Director of the Research Unit \"Economics of Change\" at the Wissenscha􀅌szentrum Berlin (WZB) and Emeritus Professor at UCL. He is the joint managing editor of the Economic Journal and serves and has served on several editorial boards. Having obtained his PhD from Humboldt University in 1996, he has published well over 80 journal articles. His research interests include (experimental) industrial organisation, political economy, issues in bounded rationality and evolutionary game theory and, rational choice approaches to drama and literature. He is the recipient of a 2004 Philip Leverhulme Prize.', 'Loukas', 'Balafoutas'),
(6, 'd2_s02_rExeter', '12:00 - 13:00', 'Streatham Court A', 'Panel Session - Mentoring', 'Chair', 'At our mentoring event for junior economists, we will organize a panel discussion to explore a range of central themes. We aim to delve into topics such as applying to jobs on the competitive econ job market and offering practical advice and strategies for securing desirable positions in the field. Moreover, we will address the challenges of publishing experimental papers to guide young economists through the intricacies of conducting and disseminating research. Work-life balance will be another focal point as we seek to help young economists navigate the demands of their profession while maintaining personal well-being. Additionally, we will discuss pathways to tenure, providing valuable insights into building successful academic careers. Lastly, the discussion on grant writing will equip participants with essential skills to secure funding for their research projects effectively. Panellists: •	Esther Blanco (University of Innsbruck)\n•	Pablo Branas (Universidad Loyola Andalucia)\n•	Brit Grosskopf (University of Exeter)\n•	Ernesto Reuben (NYU Abu Dhabi)', 'Helena', 'Fornwagner'),
(7, 'd2_s03_rExeter', '13:00 - 14:15', 'Streatham Court A', 'Panel Session - AI and Behavioural Economics', 'Chair', 'Artificial intelligence is pervading our lives. What are the key opportunities for experimental research? This round table discussion will aim to address question related to opportunities and pi􀆞alls of embracing AI in experimental research. Panellists: •	Edmond Awad (University of Exeter and University of Oxford)\n•	Chico Camargo (University of Exeter)\n•	Cecilia Chen (University of Exeter)\n•	Miriam Koschate-Reis (University of Exeter)', 'Oliver', 'Hauser'),
(8, 'd2_s04_rExeter', '18:45', 'Millers’ Bridge mill stone (for runners) front of Cathedral (for walkers)', 'Social Events', 'Run along the Exe or walk around the city centre!', 'On Wednesday, September 13, after the official end of the ESA conference, we will organize a collective running session for all the running enthusiasts (from novice to seasoned runners) who wish to explore the river Exe in a fun and active way. Choose from two routes with varying levels – 5 km or 10 km – to suit different running levels, including beginners. Route A is an easy 5 km run; Route B is an equally flat just longer run with no hills. To ensure safety and effective support, a chairperson has been appointed to supervise each route. At the end of the jogging, all participants will meet up at the “Topsham Brewery” for a drink (at their own expense ;-)).<br>For those who prefer not to run, we are organizing a walking tour through the city centre.', '', ''),
(9, 
'd1_s00_rExeter', 
'08:45 - 09:00', 
'Streatham Court A', 
'Welcome', 
'Chair', 
'Welcome to ESA 2023 at Exeter', 
'Brit', 
'Grosskopf');