name: GitHub redeploy to FEELE01
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://fgen.feele.exeter.ac.uk/git/pullAndDeploy/?accessToken=c6c94eeb-5d73-4006-8107-f92c3141a3cc&folderName=real_effort_bargaining'
        method: 'POST'
