on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://fgen.feele.exeter.ac.uk/git/pullAndDeploy/?accessToken=c6c94eeb-5d73-4006-8107-f92c3141a3cc&folderName=self-esteem'
        method: 'POST'
